name: Compile my application

on:
    workflow_dispatch:
    repository_dispatch:
        types: [veracode-build]
  
jobs:
    compile:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-java@v1
          with:
            java-version: 1.8
        - name: Build app 1 with Maven
          run: cd /app1 
            mvn clean package
        - name: Build app 2 with Maven
          run: cd /app2 
              mvn clean package
        - name: Build app 3 with Maven
          run: cd /app3 
                mvn clean package
        - name: Build app 4 with Maven
          run: cd /app4 
                  mvn clean package
        - name: Zip artefacts
          run: pwd 
            zip artefact.zip /app1/target/verademo.war /app2/target/verademo.war /app3/target/verademo.war /app4/target/verademo.war
        - uses: actions/upload-artifact@v3
          with:
            name: veracode-artifact
            path: artefact.zip
